baseURL = "http://pilgreen.github.io/in-depth/"
languageCode = "en-us"
title = "KCStar In-Depth project"

canonifyURLs = true
disableRSS = true
disableSitemap = true

staticDir = "../../assets"
newContentEditor = "vim"
